// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFimabFhYN-Vu-slgZQK0IBh7mjTOZOoc',
    appId: '1:719066244051:web:6a554570d835b723e9c526',
    messagingSenderId: '719066244051',
    projectId: 'intagram-clone-project-93fd5',
    authDomain: 'intagram-clone-project-93fd5.firebaseapp.com',
    storageBucket: 'intagram-clone-project-93fd5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpSM0X0eF5_UNpNB08_3qOhBpBR4EvDXk',
    appId: '1:719066244051:android:cc573c50a748fb67e9c526',
    messagingSenderId: '719066244051',
    projectId: 'intagram-clone-project-93fd5',
    storageBucket: 'intagram-clone-project-93fd5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZEosWaoITGlz89kj2nFZaqtha3g6ZYs0',
    appId: '1:719066244051:ios:fa587fea241e627ce9c526',
    messagingSenderId: '719066244051',
    projectId: 'intagram-clone-project-93fd5',
    storageBucket: 'intagram-clone-project-93fd5.appspot.com',
    iosBundleId: 'com.tercar.instagramClone',
  );

}